name: CI

on: 
  push:
    branches: 
      - master
    paths: 
      - src/Foodies/
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: dotnet build 
